version: 2

jobs:
  build:
    docker:
      -image: circleci/python:2-jessie
    steps:
      - checkout
      - run: 
        name: Compile Code
        command:
          mkdir output
          echo "hello world" > output/message.txt
        persist_to_workspace:
          root: output
          paths:
            - message.txt
        
  testa:
    docker:
      -image: circleci/python:2-jessie
    steps:
      - attach_workspace:
        at: output
      - run: cat output/message.txt
  testb:
    docker:
      -image: circleci/python:2-jessie
    steps:
      - attach_workspace:
        at: output
      - run: cat output/message.txt
  deploy:
    docker:
      -image: circleci/python:2-jessie
    steps:
      - attach_workspace:
        at: output
      - run: cat output/message.txt
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - testa:
        requires:
          - build
      - testb:
        requires:
          - build
      - deploy
        requires:
          - testa
          - testb
